services:

  - type: web
    name: ai-stt-backend
    runtime: docker
    plan: free

    repo: https://github.com/mdayansidd144/AI-STT.git

    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend

    healthCheckPath: /health

    envVars:
      - key: ENVIRONMENT
        value: production

      - key: WHISPER_MODEL_SIZE
        value: tiny

      - key: COMPUTE_TYPE
        value: int8

      - key: DEVICE
        value: cpu

      - key: SECRET_KEY
        sync: false

      - key: FRONTEND_URL
        sync: false

      - key: DATABASE_URL
        sync: false


  - type: web
    name: ai-stt-frontend
    runtime: static
    plan: free

    repo: https://github.com/mdayansidd144/AI-STT.git

    buildCommand: cd frontend && npm ci && npm run build

    staticPublishPath: ./frontend/dist

    envVars:
      - key: VITE_API_URL
        sync: false