# from fpdf import FPDF
# from datetime import datetime
# from pathlib import Path
# import os
# class PDFExportService:
#     def __init__(self):
#         self.output_dir = Path("./exports")
#         self.output_dir.mkdir(exist_ok=True)  
#         self.font_dir = Path("./fonts")
#         self.font_dir.mkdir(exist_ok=True)
#         # Find Hindi-supporting font
#         self.hindi_font = self._find_hindi_font()
#     def _find_hindi_font(self):
#         """Find a font that supports Hindi/Devanagari script"""
#         # Fonts that support Hindi (Devanagari script)
#         font_options = [
#             # Downloaded Noto Sans Devanagari (Best for Hindi)
#             (self.font_dir / "NotoSansDevanagari-Regular.ttf", "NotoDevanagari"),
#             (self.font_dir / "NotoSans-Regular.ttf", "NotoSans"),
#             # Windows Hindi fonts
#             ("C:/Windows/Fonts/Nirmala.ttf", "Nirmala"),
#             ("C:/Windows/Fonts/mangal.ttf", "Mangal"),
#             ("C:/Windows/Fonts/kokila.ttf", "Kokila"),
#             ("C:/Windows/Fonts/raavi.ttf", "Raavi"),
#             ("C:/Windows/Fonts/arial.ttf", "Arial"),
            
#             # Fallback
#             (None, "Helvetica"),
#         ]
#         for font_path, font_name in font_options:
#             if font_path and os.path.exists(font_path):
#                 try:
#                     FPDF.add_font(font_name, '', str(font_path), uni=True)
#                     print(f"✅ Using Hindi font: {font_name}")
#                     return font_name
#                 except Exception as e:
#                     print(f"⚠️ Failed to load {font_name}: {e}")
#                     continue
        
#         print("⚠️ No Hindi font found. Hindi characters may show as '?'")
#         return "Helvetica"
    
#     async def create_pdf(self, original: str, translated: str, source: str, target: str) -> str:
#         """Create PDF with proper Hindi support"""
#         timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
#         filename = self.output_dir / f"transcript_{timestamp}.pdf"
        
#         try:
#             pdf = FPDF()
#             pdf.add_page()
#             font_path = "./fonts/NotoSansDevanagari-Regular.ttf"
#             # Use the Hindi font for the entire document
#             pdf.add_font('MyHindiFont', '', font_path, uni=True)
#             pdf.set_font(self.hindi_font, '', 12)
#             # Title
#             pdf.set_font_size(20)
#             pdf.cell(0, 10, "AI Speech-to-Text Transcript", ln=True, align='C')
#             pdf.ln(10)
#             # Metadata
#             pdf.set_font_size(10)
#             pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
#             pdf.cell(0, 6, f"Source Language: {source.upper()}", ln=True)
#             if target:
#                 pdf.cell(0, 6, f"Target Language: {target.upper()}", ln=True)
#             pdf.ln(10) 
#             # Original Transcription
#             pdf.set_font_size(14)
#             pdf.set_font(style='B')
#             pdf.cell(0, 10, "Original Transcription", ln=True)
#             pdf.set_font_size(11)
#             pdf.set_font(style='')
            
#             # Handle text safely
#             try:
#                 pdf.multi_cell(0, 6, original)
#             except:
#                 # Fallback to Latin-1 if Unicode fails
#                 safe_text = original.encode('latin-1', errors='replace').decode('latin-1')
#                 pdf.multi_cell(0, 6, safe_text)
#             pdf.ln(10)
            
#             # Translation
#             if translated and translated.strip():
#                 pdf.set_font_size(14)
#                 pdf.set_font(style='B')
#                 pdf.cell(0, 10, f"Translation ({target.upper()})", ln=True)
#                 pdf.set_font_size(11)
#                 pdf.set_font(style='')
#                 try:
#                     pdf.multi_cell(0, 6, translated)
#                 except:
#                     safe_trans = translated.encode('latin-1', errors='replace').decode('latin-1')
#                     pdf.multi_cell(0, 6, safe_trans)
            
#             # Footer
#             pdf.set_y(-20)
#             pdf.set_font_size(8)
#             pdf.cell(0, 10, "Generated by AI Speech-to-Text System", ln=True, align='C')
#             pdf.output(str(filename))
#             print(f"✅ PDF created: {filename}")
#             return str(filename)
#         except Exception as e:
#             print(f"❌ PDF creation failed: {e}")
#             # Fallback to text file (ALWAYS works for Hindi)
#             return await self._create_text_file(original, translated, source, target, timestamp)
#     async def _create_text_file(self, original: str, translated: str, source: str, target: str, timestamp: str) -> str:
#         """Fallback: Create text file (guaranteed to work for all languages)"""
#         filename = self.output_dir / f"transcript_{timestamp}.txt"
#         with open(filename, 'w', encoding='utf-8') as f:
#             f.write("=" * 60 + "\n")
#             f.write("AI Speech-to-Text Transcript\n")
#             f.write("=" * 60 + "\n\n")
#             f.write(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
#             f.write(f"Source Language: {source.upper()}\n")
#             if target:
#                 f.write(f"Target Language: {target.upper()}\n")
#             f.write("\n" + "=" * 60 + "\n")
#             f.write("ORIGINAL TRANSCRIPTION\n")
#             f.write("=" * 60 + "\n\n")
#             f.write(original)
#             if translated:
#                 f.write("\n\n" + "=" * 60 + "\n")
#                 f.write(f"TRANSLATION ({target.upper()})\n")
#                 f.write("=" * 60 + "\n\n")
#                 f.write(translated)
#             f.write("\n\n" + "=" * 60 + "\n")
#             f.write("Generated by AI Speech-to-Text System\n")
#         print(f"✅ Text file created: {filename}")
#         return str(filename)
from fpdf import FPDF
from datetime import datetime
from pathlib import Path
import os

class PDFExportService:
    def __init__(self):
        self.output_dir = Path("./exports")
        self.output_dir.mkdir(exist_ok=True)
        
        self.font_dir = Path("./fonts")
        self.font_dir.mkdir(exist_ok=True)
        
        # Find available font (will use fallback on Render)
        self.font_name = self._find_available_font()
    
    def _find_available_font(self):
        """Find any available font - will work on Render"""
        
        # ✅ Only check fonts that exist in current environment
        font_options = [
            # Check project fonts folder first
            (self.font_dir / "NotoSansDevanagari-Regular.ttf", "NotoDevanagari"),
            (self.font_dir / "NotoSans-Regular.ttf", "NotoSans"),
            (self.font_dir / "arial.ttf", "Arial"),
            # ✅ Remove Windows paths - they don't exist on Render
            # Use default Helvetica as fallback
            (None, "Helvetica"),
        ]
        
        for font_path, font_name in font_options:
            if font_path and os.path.exists(font_path):
                try:
                    # Register the font
                    FPDF.add_font(font_name, '', str(font_path), uni=True)
                    print(f"✅ Using font: {font_name}")
                    return font_name
                except Exception as e:
                    print(f"⚠️ Failed to load {font_name}: {e}")
                    continue
        
        print("⚠️ No custom font found. Using Helvetica (English only)")
        return "Helvetica"
    
    async def create_pdf(self, original: str, translated: str, source: str, target: str) -> str:
        """Create PDF with font fallback"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = self.output_dir / f"transcript_{timestamp}.pdf"
        
        try:
            pdf = FPDF()
            pdf.add_page()
            
            # ✅ Use the available font (or fallback to Helvetica)
            pdf.set_font(self.font_name, '', 12)
            
            # Title
            pdf.set_font_size(20)
            pdf.cell(0, 10, "AI Speech-to-Text Transcript", ln=True, align='C')
            pdf.ln(10)
            
            # Metadata
            pdf.set_font_size(10)
            pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
            pdf.cell(0, 6, f"Source Language: {source.upper()}", ln=True)
            if target:
                pdf.cell(0, 6, f"Target Language: {target.upper()}", ln=True)
            pdf.ln(10)
            
            # Original Transcription
            pdf.set_font_size(14)
            pdf.set_font(style='B')
            pdf.cell(0, 10, "Original Transcription", ln=True)
            pdf.set_font_size(11)
            pdf.set_font(style='')
            
            # Handle text safely
            try:
                pdf.multi_cell(0, 6, original)
            except:
                # Fallback to Latin-1 if Unicode fails
                safe_text = original.encode('latin-1', errors='replace').decode('latin-1')
                pdf.multi_cell(0, 6, safe_text)
            pdf.ln(10)
            
            # Translation
            if translated and translated.strip():
                pdf.set_font_size(14)
                pdf.set_font(style='B')
                pdf.cell(0, 10, f"Translation ({target.upper()})", ln=True)
                pdf.set_font_size(11)
                pdf.set_font(style='')
                try:
                    pdf.multi_cell(0, 6, translated)
                except:
                    safe_trans = translated.encode('latin-1', errors='replace').decode('latin-1')
                    pdf.multi_cell(0, 6, safe_trans)
            
            # Footer
            pdf.set_y(-20)
            pdf.set_font_size(8)
            pdf.cell(0, 10, "Generated by AI Speech-to-Text System", ln=True, align='C')
            
            pdf.output(str(filename))
            print(f"✅ PDF created: {filename}")
            return str(filename)
            
        except Exception as e:
            print(f"❌ PDF creation failed: {e}")
            # Fallback to text file (ALWAYS works)
            return await self._create_text_file(original, translated, source, target, timestamp)
    
    async def _create_text_file(self, original: str, translated: str, source: str, target: str, timestamp: str) -> str:
        """Fallback: Create text file (guaranteed to work for all languages)"""
        filename = self.output_dir / f"transcript_{timestamp}.txt"
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write("=" * 60 + "\n")
            f.write("AI Speech-to-Text Transcript\n")
            f.write("=" * 60 + "\n\n")
            f.write(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"Source Language: {source.upper()}\n")
            if target:
                f.write(f"Target Language: {target.upper()}\n")
            f.write("\n" + "=" * 60 + "\n")
            f.write("ORIGINAL TRANSCRIPTION\n")
            f.write("=" * 60 + "\n\n")
            f.write(original)
            if translated:
                f.write("\n\n" + "=" * 60 + "\n")
                f.write(f"TRANSLATION ({target.upper()})\n")
                f.write("=" * 60 + "\n\n")
                f.write(translated)
            f.write("\n\n" + "=" * 60 + "\n")
            f.write("Generated by AI Speech-to-Text System\n")
        
        print(f"✅ Text file created: {filename}")
        return str(filename)